# Generated by Django 5.1.6 on 2025-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cook",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cook",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="cook_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="cook",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cook",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cook",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="cook_permissions_set", to="auth.permission"
            ),
        ),
        migrations.AlterField(
            model_name="cook",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
